apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appDescriptor.name }}
  labels:
    {{- include "gohttp-chart.labels" . | nindent 4 }}
    project: {{ .Values.appDescriptor.project }}
    name: {{ .Values.appDescriptor.name }}
    env: {{ .Values.appDescriptor.env }}
    server: {{ .Values.appDescriptor.server }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gohttp-chart.selectorLabels" . | nindent 4 }}
