{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gohttp-chart.serviceAccountName" . }}
  labels:
    {{- include "gohttp-chart.labels" . | nindent 4 }}
    project: {{ .Values.appDescriptor.project }}
    name: {{ .Values.appDescriptor.name }}
    env: {{ .Values.appDescriptor.env }}
    server: {{ .Values.appDescriptor.server }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
